package entity;

import java.util.Date;

public class Activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String activityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityType
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String activitytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityTitle
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String activitytitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityDesc
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String activitydesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityDate
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private Date activitydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityHot
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private Integer activityhot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityJoin
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String activityjoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityLauncher
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String activitylauncher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityAttribute
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String activityattribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activityCloseDate
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private Date activityclosedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityId
     *
     * @return the value of activity.activityId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityId
     *
     * @param activityid the value for activity.activityId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivityid(String activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityType
     *
     * @return the value of activity.activityType
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getActivitytype() {
        return activitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityType
     *
     * @param activitytype the value for activity.activityType
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivitytype(String activitytype) {
        this.activitytype = activitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityTitle
     *
     * @return the value of activity.activityTitle
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getActivitytitle() {
        return activitytitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityTitle
     *
     * @param activitytitle the value for activity.activityTitle
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivitytitle(String activitytitle) {
        this.activitytitle = activitytitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityDesc
     *
     * @return the value of activity.activityDesc
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getActivitydesc() {
        return activitydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityDesc
     *
     * @param activitydesc the value for activity.activityDesc
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivitydesc(String activitydesc) {
        this.activitydesc = activitydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityDate
     *
     * @return the value of activity.activityDate
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public Date getActivitydate() {
        return activitydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityDate
     *
     * @param activitydate the value for activity.activityDate
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivitydate(Date activitydate) {
        this.activitydate = activitydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityHot
     *
     * @return the value of activity.activityHot
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public Integer getActivityhot() {
        return activityhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityHot
     *
     * @param activityhot the value for activity.activityHot
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivityhot(Integer activityhot) {
        this.activityhot = activityhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityJoin
     *
     * @return the value of activity.activityJoin
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getActivityjoin() {
        return activityjoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityJoin
     *
     * @param activityjoin the value for activity.activityJoin
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivityjoin(String activityjoin) {
        this.activityjoin = activityjoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityLauncher
     *
     * @return the value of activity.activityLauncher
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getActivitylauncher() {
        return activitylauncher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityLauncher
     *
     * @param activitylauncher the value for activity.activityLauncher
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivitylauncher(String activitylauncher) {
        this.activitylauncher = activitylauncher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityAttribute
     *
     * @return the value of activity.activityAttribute
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getActivityattribute() {
        return activityattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityAttribute
     *
     * @param activityattribute the value for activity.activityAttribute
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivityattribute(String activityattribute) {
        this.activityattribute = activityattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activityCloseDate
     *
     * @return the value of activity.activityCloseDate
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public Date getActivityclosedate() {
        return activityclosedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activityCloseDate
     *
     * @param activityclosedate the value for activity.activityCloseDate
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setActivityclosedate(Date activityclosedate) {
        this.activityclosedate = activityclosedate;
    }
}