package entity;

import java.util.Date;

public class Activitycomments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activitycomments.cid
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activitycomments.statues
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    private String statues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activitycomments.target
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activitycomments.comment
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activitycomments.conDate
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    private Date condate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activitycomments.acid
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    private String acid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitycomments.cid
     *
     * @return the value of activitycomments.cid
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitycomments.cid
     *
     * @param cid the value for activitycomments.cid
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitycomments.statues
     *
     * @return the value of activitycomments.statues
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public String getStatues() {
        return statues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitycomments.statues
     *
     * @param statues the value for activitycomments.statues
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public void setStatues(String statues) {
        this.statues = statues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitycomments.target
     *
     * @return the value of activitycomments.target
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitycomments.target
     *
     * @param target the value for activitycomments.target
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitycomments.comment
     *
     * @return the value of activitycomments.comment
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitycomments.comment
     *
     * @param comment the value for activitycomments.comment
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitycomments.conDate
     *
     * @return the value of activitycomments.conDate
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public Date getCondate() {
        return condate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitycomments.conDate
     *
     * @param condate the value for activitycomments.conDate
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public void setCondate(Date condate) {
        this.condate = condate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activitycomments.acid
     *
     * @return the value of activitycomments.acid
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public String getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activitycomments.acid
     *
     * @param acid the value for activitycomments.acid
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    public void setAcid(String acid) {
        this.acid = acid;
    }
}