package entity;


import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Announce implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.aid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.status
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.content
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.date
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.hot
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private Integer hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.attribute
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String attribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announce.userid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String userid;

    private List<Comments> comments;

    public Announce() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.aid
     *
     * @return the value of announce.aid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */


    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.aid
     *
     * @param aid the value for announce.aid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setAid(String aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.status
     *
     * @return the value of announce.status
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.status
     *
     * @param status the value for announce.status
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.content
     *
     * @return the value of announce.content
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.content
     *
     * @param content the value for announce.content
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.date
     *
     * @return the value of announce.date
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.date
     *
     * @param date the value for announce.date
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.hot
     *
     * @return the value of announce.hot
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public Integer getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.hot
     *
     * @param hot the value for announce.hot
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setHot(Integer hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.attribute
     *
     * @return the value of announce.attribute
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.attribute
     *
     * @param attribute the value for announce.attribute
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announce.userid
     *
     * @return the value of announce.userid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announce.userid
     *
     * @param userid the value for announce.userid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public List<Comments> getComments() {
        return comments;
    }

    public void setComments(List<Comments> comments) {
        this.comments = comments;
    }

    @Override
    public String toString() {
        return "Announce{" +
                "aid='" + aid + '\'' +
                ", status='" + status + '\'' +
                ", content='" + content + '\'' +
                ", date=" + date +
                ", hot=" + hot +
                ", attribute='" + attribute + '\'' +
                ", userid='" + userid + '\'' +
                ", comments=" + comments +
                '}';
    }
}