package entity;

import java.util.Date;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.cid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.statues
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String statues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.target
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.comment
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.conDate
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private Date condate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.acid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    private String acid;

    private Announce announce;


    public Comments() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.cid
     *
     * @return the value of comments.cid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.cid
     *
     * @param cid the value for comments.cid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.statues
     *
     * @return the value of comments.statues
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getStatues() {
        return statues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.statues
     *
     * @param statues the value for comments.statues
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setStatues(String statues) {
        this.statues = statues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.target
     *
     * @return the value of comments.target
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.target
     *
     * @param target the value for comments.target
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.comment
     *
     * @return the value of comments.comment
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.comment
     *
     * @param comment the value for comments.comment
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.conDate
     *
     * @return the value of comments.conDate
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public Date getCondate() {
        return condate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.conDate
     *
     * @param condate the value for comments.conDate
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setCondate(Date condate) {
        this.condate = condate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.acid
     *
     * @return the value of comments.acid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public String getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.acid
     *
     * @param acid the value for comments.acid
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    public void setAcid(String acid) {
        this.acid = acid;
    }

    public Announce getAnnounce() {
        return announce;
    }

    public void setAnnounce(Announce announce) {
        this.announce = announce;
    }

    @Override
    public String toString() {
        return "Comments{" +
                "cid='" + cid + '\'' +
                ", statues='" + statues + '\'' +
                ", target='" + target + '\'' +
                ", comment='" + comment + '\'' +
                ", condate=" + condate +
                ", acid='" + acid + '\'' +
                ", announce=" + announce +
                '}';
    }
}