package entity;

public class Numorg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column numorg.userId
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column numorg.orgid
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column numorg.numposition
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String numposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column numorg.numname
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String numname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column numorg.userId
     *
     * @return the value of numorg.userId
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column numorg.userId
     *
     * @param userid the value for numorg.userId
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column numorg.orgid
     *
     * @return the value of numorg.orgid
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column numorg.orgid
     *
     * @param orgid the value for numorg.orgid
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column numorg.numposition
     *
     * @return the value of numorg.numposition
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getNumposition() {
        return numposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column numorg.numposition
     *
     * @param numposition the value for numorg.numposition
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setNumposition(String numposition) {
        this.numposition = numposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column numorg.numname
     *
     * @return the value of numorg.numname
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getNumname() {
        return numname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column numorg.numname
     *
     * @param numname the value for numorg.numname
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setNumname(String numname) {
        this.numname = numname;
    }
}