package entity;

import java.util.Date;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgId
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgName
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String orgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgDesc
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String orgdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgHead
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String orghead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgAdmin
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String orgadmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.orgDate
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private Date orgdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgId
     *
     * @return the value of organization.orgId
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgId
     *
     * @param orgid the value for organization.orgId
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgName
     *
     * @return the value of organization.orgName
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgName
     *
     * @param orgname the value for organization.orgName
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgDesc
     *
     * @return the value of organization.orgDesc
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getOrgdesc() {
        return orgdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgDesc
     *
     * @param orgdesc the value for organization.orgDesc
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrgdesc(String orgdesc) {
        this.orgdesc = orgdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgHead
     *
     * @return the value of organization.orgHead
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getOrghead() {
        return orghead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgHead
     *
     * @param orghead the value for organization.orgHead
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrghead(String orghead) {
        this.orghead = orghead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgAdmin
     *
     * @return the value of organization.orgAdmin
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getOrgadmin() {
        return orgadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgAdmin
     *
     * @param orgadmin the value for organization.orgAdmin
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrgadmin(String orgadmin) {
        this.orgadmin = orgadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.orgDate
     *
     * @return the value of organization.orgDate
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public Date getOrgdate() {
        return orgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.orgDate
     *
     * @param orgdate the value for organization.orgDate
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrgdate(Date orgdate) {
        this.orgdate = orgdate;
    }
}