package entity;

import java.util.Date;

public class Orgmsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgmsg.orgid
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgmsg.msgType
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String msgtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgmsg.msgData
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String msgdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgmsg.msgFile
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private String msgfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgmsg.msgDate
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    private Date msgdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgmsg.orgid
     *
     * @return the value of orgmsg.orgid
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgmsg.orgid
     *
     * @param orgid the value for orgmsg.orgid
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgmsg.msgType
     *
     * @return the value of orgmsg.msgType
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgmsg.msgType
     *
     * @param msgtype the value for orgmsg.msgType
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setMsgtype(String msgtype) {
        this.msgtype = msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgmsg.msgData
     *
     * @return the value of orgmsg.msgData
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getMsgdata() {
        return msgdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgmsg.msgData
     *
     * @param msgdata the value for orgmsg.msgData
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setMsgdata(String msgdata) {
        this.msgdata = msgdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgmsg.msgFile
     *
     * @return the value of orgmsg.msgFile
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public String getMsgfile() {
        return msgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgmsg.msgFile
     *
     * @param msgfile the value for orgmsg.msgFile
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setMsgfile(String msgfile) {
        this.msgfile = msgfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgmsg.msgDate
     *
     * @return the value of orgmsg.msgDate
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public Date getMsgdate() {
        return msgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgmsg.msgDate
     *
     * @param msgdate the value for orgmsg.msgDate
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    public void setMsgdate(Date msgdate) {
        this.msgdate = msgdate;
    }
}