package entity;

public class Patriarch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patriarch.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patriarch.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patriarch.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patriarch.id
     *
     * @return the value of patriarch.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patriarch.id
     *
     * @param id the value for patriarch.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patriarch.name
     *
     * @return the value of patriarch.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patriarch.name
     *
     * @param name the value for patriarch.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patriarch.gender
     *
     * @return the value of patriarch.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patriarch.gender
     *
     * @param gender the value for patriarch.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }
}