package entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentNum
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String studentnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.dept
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classes
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String classes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentNum
     *
     * @return the value of student.studentNum
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getStudentnum() {
        return studentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentNum
     *
     * @param studentnum the value for student.studentNum
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setStudentnum(String studentnum) {
        this.studentnum = studentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.dept
     *
     * @return the value of student.dept
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.dept
     *
     * @param dept the value for student.dept
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classes
     *
     * @return the value of student.classes
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classes
     *
     * @param classes the value for student.classes
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setClasses(String classes) {
        this.classes = classes;
    }
}