package entity;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacherNum
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String teachernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.dept
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.classes
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String classes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gender
     *
     * @return the value of teacher.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gender
     *
     * @param gender the value for teacher.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacherNum
     *
     * @return the value of teacher.teacherNum
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getTeachernum() {
        return teachernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacherNum
     *
     * @param teachernum the value for teacher.teacherNum
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setTeachernum(String teachernum) {
        this.teachernum = teachernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.dept
     *
     * @return the value of teacher.dept
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.dept
     *
     * @param dept the value for teacher.dept
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.classes
     *
     * @return the value of teacher.classes
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.classes
     *
     * @param classes the value for teacher.classes
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setClasses(String classes) {
        this.classes = classes;
    }
}