package entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.e_mail
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String eMail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isactivite
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private Boolean isactivite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.niclname
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String niclname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String head;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthdy
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private Date birthdy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.declaration
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String declaration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.partId
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String partid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.partname
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    private String partname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.e_mail
     *
     * @return the value of user.e_mail
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String geteMail() {
        return eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.e_mail
     *
     * @param eMail the value for user.e_mail
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void seteMail(String eMail) {
        this.eMail = eMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isactivite
     *
     * @return the value of user.isactivite
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public Boolean getIsactivite() {
        return isactivite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isactivite
     *
     * @param isactivite the value for user.isactivite
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setIsactivite(Boolean isactivite) {
        this.isactivite = isactivite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.niclname
     *
     * @return the value of user.niclname
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getNiclname() {
        return niclname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.niclname
     *
     * @param niclname the value for user.niclname
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setNiclname(String niclname) {
        this.niclname = niclname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head
     *
     * @return the value of user.head
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head
     *
     * @param head the value for user.head
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setHead(String head) {
        this.head = head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthdy
     *
     * @return the value of user.birthdy
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public Date getBirthdy() {
        return birthdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthdy
     *
     * @param birthdy the value for user.birthdy
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setBirthdy(Date birthdy) {
        this.birthdy = birthdy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.declaration
     *
     * @return the value of user.declaration
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.declaration
     *
     * @param declaration the value for user.declaration
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setDeclaration(String declaration) {
        this.declaration = declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.partId
     *
     * @return the value of user.partId
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getPartid() {
        return partid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.partId
     *
     * @param partid the value for user.partId
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setPartid(String partid) {
        this.partid = partid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.partname
     *
     * @return the value of user.partname
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public String getPartname() {
        return partname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.partname
     *
     * @param partname the value for user.partname
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    public void setPartname(String partname) {
        this.partname = partname;
    }

    @Override
    public boolean equals(Object obj) {
        User user = (User)obj;
        if(this.getPassword().equals(user.getPassword())
                && this.getUsername().equals(user.getUsername())){
            return true;
        }
        return false;
    }
}