package entity;

public class Vote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.voteId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String voteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.voteActivityId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String voteactivityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.voteImgHead
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String voteimghead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.voteDesc
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private String votedesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.voteCount
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    private Integer votecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.voteId
     *
     * @return the value of vote.voteId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.voteId
     *
     * @param voteid the value for vote.voteId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setVoteid(String voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.voteActivityId
     *
     * @return the value of vote.voteActivityId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getVoteactivityid() {
        return voteactivityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.voteActivityId
     *
     * @param voteactivityid the value for vote.voteActivityId
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setVoteactivityid(String voteactivityid) {
        this.voteactivityid = voteactivityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.voteImgHead
     *
     * @return the value of vote.voteImgHead
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getVoteimghead() {
        return voteimghead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.voteImgHead
     *
     * @param voteimghead the value for vote.voteImgHead
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setVoteimghead(String voteimghead) {
        this.voteimghead = voteimghead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.voteDesc
     *
     * @return the value of vote.voteDesc
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public String getVotedesc() {
        return votedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.voteDesc
     *
     * @param votedesc the value for vote.voteDesc
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setVotedesc(String votedesc) {
        this.votedesc = votedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.voteCount
     *
     * @return the value of vote.voteCount
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public Integer getVotecount() {
        return votecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.voteCount
     *
     * @param votecount the value for vote.voteCount
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    public void setVotecount(Integer votecount) {
        this.votecount = votecount;
    }
}