package dao;

import org.springframework.stereotype.Repository;

import entity.Activitycomments;

@Repository
public interface ActivitycommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitycomments
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitycomments
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    int insert(Activitycomments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitycomments
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    int insertSelective(Activitycomments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitycomments
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    Activitycomments selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitycomments
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    int updateByPrimaryKeySelective(Activitycomments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activitycomments
     *
     * @mbggenerated Mon Mar 13 08:52:26 CST 2017
     */
    int updateByPrimaryKey(Activitycomments record);
}