package dao;

import entity.Activity;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    int insertSelective(Activity record);

    Activity selectActivityJoinById(String activityId);

    int updateActivity(Activity activity);
}