package dao;

import java.util.List;

import entity.Announce;
import entity.PageParam;

public interface AnnounceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    int insert(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    int insertSelective(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    Announce selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    int updateByPrimaryKeySelective(Announce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announce
     *
     * @mbggenerated Tue Mar 07 22:06:13 CST 2017
     */
    int updateByPrimaryKey(Announce record);

    List<Announce> getUserAnnounce(PageParam pageParam);

    String findSourceAnnounceById(String aid);

    //int addAnnounce(Announce announce);
}