package dao;

import entity.Numorg;

public interface NumorgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table numorg
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    int insert(Numorg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table numorg
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    int insertSelective(Numorg record);
}