package dao;

import entity.Organization;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Thu Mar 16 14:33:20 CST 2017
     */
    int insertSelective(Organization record);
}