package dao;

import entity.Patriarch;

public interface PatriarchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patriarch
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patriarch
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    int insert(Patriarch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patriarch
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    int insertSelective(Patriarch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patriarch
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    Patriarch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patriarch
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    int updateByPrimaryKeySelective(Patriarch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patriarch
     *
     * @mbggenerated Thu Mar 02 10:14:48 CST 2017
     */
    int updateByPrimaryKey(Patriarch record);
}