package dao;

import entity.Vote;

public interface VoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    int insert(Vote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbggenerated Fri Mar 10 08:53:51 CST 2017
     */
    int insertSelective(Vote record);
}